// Generated by CoffeeScript 1.5.0
(function() {
  var AlertCtrl, ConfirmationCtrl, DialogCtrl, FormCtrl, app;

  app = angular.module("bitcoinSecured", ['ui.bootstrap']);

  app.factory("txevent", [
    '$window', function($window) {
      return {
        notify: function(msg) {
          return $window.alert(msg);
        },
        doTrans: function(tx_data) {
          var eckey, msg, secret, sendTx, tx;
          secret = $window.Bitcoin.Base58.decode(tx_data.sec).slice(1, 33);
          eckey = new $window.Bitcoin.ECKey(secret);
          tx = new $window.TX(eckey);
          tx.parseInputs(tx_data.unspent, tx.getAddress());
          sendTx = tx.construct(tx_data.dest, tx_data.addr, tx_data.amount, tx_data.fee);
          console.log($window.Crypto.util.bytesToHex(sendTx.serialize()));
          msg = {};
          msg.rawtx = $window.Crypto.util.bytesToHex(sendTx.serialize());
          msg.tx_data = tx_data;
          return msg;
        }
      };
    }
  ]);

  app.directive("qrCode", [
    '$window', function($window) {
      return {
        template: "<div id='qr-code'></div>",
        restrict: 'E',
        scope: {
          localQrMsg: '=myAttr'
        },
        link: function(scope, element, attrs) {
          var el, qr;
          el = angular.element(element);
          return qr = new $window.QRCode(el[0], scope.localQrMsg);
        }
      };
    }
  ]);

  app.controller("FormCtrl", FormCtrl = function($scope, $http, $dialog, txevent) {
    $scope.buttonState = {};
    $scope.buttonState.qrcodestate = "disabled";
    $scope.clearAll = function(e) {
      e.preventDefault();
      $scope.transaction_data = "";
      $scope.rawtx = "";
      return $scope.secret = "";
    };
    $scope.openConfirmation = function(msg) {
      var d, opts, t, tx_data;
      tx_data = msg.tx_data;
      t = "<div id=\"modal\">\n  <div class=\"modal-header\">\n    <h3>Raw Transaction Confirmation</h3>\n  </div>\n  <div class=\"modal-body\">\n  You are sending <strong>" + tx_data.amount + " btc</strong> from cold storage address:<br>\n  <strong>" + tx_data.addr + "</strong><br>\n  to Bitcoin address:<br>\n  <strong>" + tx_data.dest + "</strong><br>\n  for a transaction fee of <strong>" + tx_data.fee + "</strong>\n  <p>If these are the amounts and recipient you intended, please click OK below.\n  Otherwise, please cancel the transaction and repeat the online portion</p>\n  </div>\n  <div class=\"modal-footer\">\n    <button ng-click=\"close('cancel')\" class=\"btn\" >Cancel</button>\n    <button ng-click=\"close('ok')\" class=\"btn btn-primary\" >OK</button>\n  </div>\n</div>";
      opts = {
        backdrop: true,
        template: t,
        controller: "ConfirmationCtrl"
      };
      d = $dialog.dialog(opts);
      return d.open().then(function(result) {
        if (result === 'ok') {
          return $scope.rawtx = msg.rawtx;
        } else {
          return alert("Your transaction is cancelled");
        }
      });
    };
    $scope.openDialog = function(msg) {
      var d, opts, t;
      t = "<div id=\"modal\">\n    <qr-code my-attr=\"msg\"></qr-code>\n</div>";
      opts = {
        template: t,
        dialogClass: "modal qr-modal",
        controller: "DialogCtrl",
        backdrop: true,
        resolve: {
          msg: function() {
            return angular.copy(msg);
          }
        }
      };
      d = $dialog.dialog(opts);
      return d.open().then(function(result) {
        if (result === 'ok') {
          return console.log("Your transaction is ok");
        } else {
          return console.log("Your transaction is cancelled");
        }
      });
    };
    $scope.showQr = function() {
      return $scope.openDialog($scope.rawtx);
    };
    return $scope.processForm = function() {
      var msg, tx;
      console.log("processing form now");
      tx = JSON.parse($scope.transaction_data);
      tx.sec = $scope.secret;
      msg = txevent.doTrans(tx);
      $scope.openConfirmation(msg);
      return $scope.buttonState.qrcodestate = "";
    };
  });

  app.controller("ConfirmationCtrl", ConfirmationCtrl = function($scope, dialog) {
    return $scope.close = function(result) {
      return dialog.close(result);
    };
  });

  app.controller("DialogCtrl", DialogCtrl = function($scope, msg, dialog) {
    $scope.close = function(result) {
      return dialog.close(result);
    };
    return $scope.msg = msg;
  });

  app.controller("AlertCtrl", AlertCtrl = function($scope) {
    $scope.alerts = [
      {
        type: "error",
        msg: "Bitcoin Secured 0.1 is beta quality software. As such, there is a small but real chance of software error. Please don't use this system to transfer large amounts of Bitcoins until this beta notice is removed."
      }
    ];
    $scope.addAlert = function(msg) {
      return $scope.alerts.push({
        msg: msg
      });
    };
    return $scope.closeAlert = function(index) {
      return $scope.alerts.splice(index, 1);
    };
  });

}).call(this);
