// Generated by CoffeeScript 1.5.0
(function() {
  var DialogCtrl, FormCtrl, app;

  app = angular.module("bitcoinSecured", ['ui.bootstrap']);

  app.factory("txevent", [
    '$window', function($window) {
      return {
        notify: function(msg) {
          return $window.alert(msg);
        },
        doTrans: function(tx_data) {
          var eckey, msg, secret, sendTx, tx;
          secret = $window.Bitcoin.Base58.decode(tx_data.sec).slice(1, 33);
          eckey = new $window.Bitcoin.ECKey(secret);
          tx = new $window.TX(eckey);
          tx.parseInputs(tx_data.unspent, tx.getAddress());
          sendTx = tx.construct(tx_data.dest, tx_data.addr, tx_data.amount, tx_data.fee);
          console.log($window.Crypto.util.bytesToHex(sendTx.serialize()));
          msg = {};
          msg.rawtx = $window.Crypto.util.bytesToHex(sendTx.serialize());
          msg.tx_data = tx_data;
          return msg;
        }
      };
    }
  ]);

  app.factory("qrcode", [
    '$window', function($window) {
      return {
        renderQR: function(msg) {
          $("#qr-code").empty();
          return new $window.QRCode($("#qr-code").get(0), msg);
        },
        hideQR: function() {
          return $("#qr-code").empty();
        }
      };
    }
  ]);

  app.controller("FormCtrl", FormCtrl = function($scope, $http, $dialog, txevent, qrcode) {
    $scope.clearAll = function(e) {
      e.preventDefault();
      $scope.transaction_data = "";
      $scope.rawtx = "";
      $scope.secret = "";
      return qrcode.hideQR();
    };
    $scope.openDialog = function(msg) {
      var d, opts, t, tx_data;
      tx_data = msg.tx_data;
      t = "<div id=\"modal\">\n  <div class=\"modal-header\">\n    <h3>Raw Transaction Confirmation</h3>\n  </div>\n  <div class=\"modal-body\">\n  You are sending <strong>" + tx_data.amount + " btc</strong> from cold storage address:<br>\n  <strong>" + tx_data.addr + "</strong><br>\n  to Bitcoin address:<br>\n  <strong>" + tx_data.dest + "</strong><br>\n  for a transaction fee of <strong>" + tx_data.fee + "</strong>\n  <p>If these are the amounts and recipient you intended, please click OK below.\n  Otherwise, please cancel the transaction and repeat the online portion</p>\n  </div>\n  <div class=\"modal-footer\">\n    <button ng-click=\"close('cancel')\" class=\"btn\" >Cancel</button>\n    <button ng-click=\"close('ok')\" class=\"btn btn-primary\" >OK</button>\n  </div>\n</div>";
      opts = {
        backdrop: true,
        template: t,
        controller: "DialogCtrl"
      };
      d = $dialog.dialog(opts);
      return d.open().then(function(result) {
        if (result === 'ok') {
          $scope.rawtx = msg.rawtx;
          return qrcode.renderQR(msg.rawtx);
        } else {
          return alert("Your transaction is cancelled");
        }
      });
    };
    return $scope.processForm = function() {
      var msg, tx;
      console.log("processing form now");
      tx = JSON.parse($scope.transaction_data);
      tx.sec = $scope.secret;
      msg = txevent.doTrans(tx);
      return $scope.openDialog(msg);
    };
  });

  app.controller("DialogCtrl", DialogCtrl = function($scope, dialog) {
    return $scope.close = function(result) {
      return dialog.close(result);
    };
  });

}).call(this);
