// Generated by CoffeeScript 1.5.0
(function() {
  var btcstr2bignum, dumpScript, endian, errv, isEmpty, parseScript, readBuffer, readString, readVarInt, root, tx_parseBCI, u16, u32, u64, u8, uint;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.TX = (function() {

    function TX(eckey) {
      this.inputs = [];
      this.outputs = [];
      this.eckey = eckey;
      this.balance = 0;
    }

    TX.prototype.addOutput = function(addr, fval) {
      return this.outputs.push({
        address: addr,
        value: fval
      });
    };

    TX.prototype.getBalance = function() {
      return this.balance;
    };

    TX.prototype.getAddress = function() {
      return this.eckey.getBitcoinAddress().toString();
    };

    TX.prototype.parseInputs = function(text, address) {
      var res;
      res = tx_parseBCI(text, address);
      console.log("here is parseInputs");
      this.balance = res.balance;
      return this.inputs = res.unspenttxs;
    };

    TX.prototype.construct = function() {
      var address, b64hash, connectedScript, fval, hash, hashType, i, index, pubKey, pubKeyHash, script, selectedOuts, sendTx, signature, txin, value;
      sendTx = new Bitcoin.Transaction();
      selectedOuts = [];
      for (hash in this.inputs) {
        if (!this.inputs.hasOwnProperty(hash)) {
          continue;
        }
        for (index in this.inputs[hash]) {
          if (!this.inputs[hash].hasOwnProperty(index)) {
            continue;
          }
          script = parseScript(this.inputs[hash][index].script);
          b64hash = Crypto.util.bytesToBase64(Crypto.util.hexToBytes(hash));
          txin = new Bitcoin.TransactionIn({
            outpoint: {
              hash: b64hash,
              index: index
            },
            script: script,
            sequence: 4294967295
          });
          selectedOuts.push(txin);
          sendTx.addInput(txin);
        }
      }
      for (i in this.outputs) {
        address = this.outputs[i].address;
        fval = this.outputs[i].value;
        value = new BigInteger("" + Math.round(fval * 1e8), 10);
        sendTx.addOutput(new Bitcoin.Address(address), value);
      }
      hashType = 1;
      i = 0;
      while (i < sendTx.ins.length) {
        connectedScript = selectedOuts[i].script;
        hash = sendTx.hashTransactionForSignature(connectedScript, i, hashType);
        pubKeyHash = connectedScript.simpleOutPubKeyHash();
        signature = this.eckey.sign(hash);
        signature.push(parseInt(hashType, 10));
        pubKey = this.eckey.getPub();
        script = new Bitcoin.Script();
        script.writeBytes(signature);
        script.writeBytes(pubKey);
        sendTx.ins[i].script = script;
        i++;
      }
      return sendTx;
    };

    TX.prototype.deserialize = function(bytes) {
      var f, i, lock_time, n, op, script, sendTx, seq, tx_ver, txin, txout, value, vin_sz, vout_sz;
      sendTx = new Bitcoin.Transaction();
      f = bytes.slice(0);
      tx_ver = u32(f);
      vin_sz = readVarInt(f);
      if (errv(vin_sz)) {
        return null;
      }
      i = 0;
      while (i < vin_sz) {
        op = readBuffer(f, 32);
        n = u32(f);
        script = readString(f);
        seq = u32(f);
        txin = new Bitcoin.TransactionIn({
          outpoint: {
            hash: Crypto.util.bytesToBase64(op),
            index: n
          },
          script: new Bitcoin.Script(script),
          sequence: seq
        });
        sendTx.addInput(txin);
        i++;
      }
      vout_sz = readVarInt(f);
      if (errv(vout_sz)) {
        return null;
      }
      i = 0;
      while (i < vout_sz) {
        value = u64(f);
        script = readString(f);
        txout = new Bitcoin.TransactionOut({
          value: value,
          script: new Bitcoin.Script(script)
        });
        sendTx.addOutput(txout);
        i++;
      }
      lock_time = u32(f);
      sendTx.lock_time = lock_time;
      return sendTx;
    };

    return TX;

  })();

  uint = function(f, size) {
    var b, bytes, i, n, pos;
    if (f.length < size) {
      return 0;
    }
    bytes = f.slice(0, size);
    pos = 1;
    n = 0;
    i = 0;
    while (i < size) {
      b = f.shift();
      n += b * pos;
      pos *= 256;
      i++;
    }
    if (size <= 4) {
      return n;
    } else {
      return bytes;
    }
  };

  u8 = function(f) {
    return uint(f, 1);
  };

  u16 = function(f) {
    return uint(f, 2);
  };

  u32 = function(f) {
    return uint(f, 4);
  };

  u64 = function(f) {
    return uint(f, 8);
  };

  errv = function(val) {
    return val instanceof BigInteger || val > 0xffff;
  };

  readBuffer = function(f, size) {
    var i, res;
    res = f.slice(0, size);
    i = 0;
    while (i < size) {
      f.shift();
      i++;
    }
    return res;
  };

  readString = function(f) {
    var len;
    len = readVarInt(f);
    if (errv(len)) {
      return [];
    }
    return readBuffer(f, len);
  };

  readVarInt = function(f) {
    var t;
    t = u8(f);
    if (t === 0xfd) {
      return u16(f);
    } else if (t === 0xfe) {
      return u32(f);
    } else if (t === 0xff) {
      return u64(f);
    } else {
      return t;
    }
  };

  dumpScript = function(script) {
    var chunk, i, op, out;
    out = [];
    i = 0;
    while (i < script.chunks.length) {
      chunk = script.chunks[i];
      op = new Bitcoin.Opcode(chunk);
      if (typeof chunk === "number") {
        out.push(op.toString());
      } else {
        out.push(Crypto.util.bytesToHex(chunk));
      }
      i++;
    }
    return out.join(" ");
  };

  tx_parseBCI = function(data, address) {
    var balance, i, lilendHash, o, r, script, txs, unspenttxs, value;
    r = JSON.parse(data);
    txs = r.unspent_outputs;
    if (!txs) {
      throw "Not a BCI format";
    }
    delete unspenttxs;
    unspenttxs = {};
    balance = BigInteger.ZERO;
    for (i in txs) {
      o = txs[i];
      lilendHash = o.tx_hash;
      script = dumpScript(new Bitcoin.Script(Crypto.util.hexToBytes(o.script)));
      value = new BigInteger("" + o.value, 10);
      if (!(lilendHash in unspenttxs)) {
        unspenttxs[lilendHash] = {};
      }
      unspenttxs[lilendHash][o.tx_output_n] = {
        amount: value,
        script: script
      };
      balance = balance.add(value);
    }
    return {
      balance: balance,
      unspenttxs: unspenttxs
    };
  };

  isEmpty = function(ob) {
    var i;
    for (i in ob) {
      if (ob.hasOwnProperty(i)) {
        return false;
      }
    }
    return true;
  };

  endian = function(string) {
    var i, out;
    out = [];
    i = string.length;
    while (i > 0) {
      out.push(string.substring(i - 2, i));
      i -= 2;
    }
    return out.join("");
  };

  btcstr2bignum = function(btc) {
    var diff, i, mul, value;
    i = btc.indexOf(".");
    value = new BigInteger(btc.replace(/\./, ""));
    diff = 9 - (btc.length - i);
    if (i === -1) {
      mul = "100000000";
    } else if (diff < 0) {
      return value.divide(new BigInteger(Math.pow(10, -1 * diff).toString()));
    } else {
      mul = Math.pow(10, diff).toString();
    }
    return value.multiply(new BigInteger(mul));
  };

  parseScript = function(script) {
    var i, newScript, s;
    newScript = new Bitcoin.Script();
    s = script.split(" ");
    for (i in s) {
      if (Bitcoin.Opcode.map.hasOwnProperty(s[i])) {
        newScript.writeOp(Bitcoin.Opcode.map[s[i]]);
      } else {
        newScript.writeBytes(Crypto.util.hexToBytes(s[i]));
      }
    }
    return newScript;
  };

}).call(this);
